# Generated by Django 5.0.6 on 2024-06-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_autor_options_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
