# Generated by Django 5.0.6 on 2024-07-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_autor_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='autor',
            unique_together={('nombre', 'apellido')},
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('nombre', 'apellido')},
        ),
    ]
